http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  searchsrv:
    host: localhost
    paths: '/api/search/'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  searchsrv:
    url: 'http://localhost:3000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - searchsrv
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: searchsrv 
              changeOrigin: true
    
